-- Supabase Schema for mperium Appliance
-- Auto-generated from data/*.json

-- 1) blog.json -> blog
create table if not exists public.blog (
  id bigint primary key,
  slug text unique not null,
  title text not null,
  excerpt text,
  category text,
  "readTime" text,
  "publishedAt" text,
  image text,
  content text
);

-- 2) locations.json -> locations
create table if not exists public.locations (
  slug text primary key,
  name text not null,
  region text,
  description text,
  "mapEmbedUrl" text,
  "subAreas" jsonb default '[]'::jsonb
);

-- 3) brands.json -> brands
create table if not exists public.brands (
  slug text primary key,
  title text not null,
  description text,
  image text,
  premium boolean default false
);

-- 4) contact.json -> contact
create table if not exists public.contact (
  id bigint generated by default as identity primary key,
  phone text,
  "phoneHref" text,
  email text,
  location text,
  "socialMedia" jsonb default '[]'::jsonb,
  reviews jsonb default '{}'::jsonb
);

-- 5) faq.json -> faq
create table if not exists public.faq (
  id bigint generated by default as identity primary key,
  question text not null,
  answer text not null
);
create unique index if not exists faq_question_uidx on public.faq (question);

-- 6) metadata.json -> metadata
create table if not exists public.metadata (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  keywords text
);

-- 7) service-details.json -> service_details
create table if not exists public.service_details (
  slug text primary key,
  title text not null,
  description text,
  image text
);

-- 8) services-commercial.json -> services_commercial
create table if not exists public.services_commercial (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  href text,
  icon text
);

-- 9) services-residential.json -> services_residential
create table if not exists public.services_residential (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  href text,
  icon text
);

-- 10) testimonials.json -> testimonials
create table if not exists public.testimonials (
  id bigint generated by default as identity primary key,
  initials text,
  name text not null,
  location text,
  text text not null,
  avatar text
);

-- 11) why.json -> why
create table if not exists public.why (
  id bigint generated by default as identity primary key,
  title text not null,
  description text not null,
  icon text not null
);

-- Backward-compat migration for existing installations where why table was jsonb-based
alter table public.why add column if not exists title text;
alter table public.why add column if not exists description text;
alter table public.why add column if not exists icon text;

-- 12) areas.json -> areas
create table if not exists public.areas (
  id bigint generated by default as identity primary key,
  city text not null,
  page_index integer not null default 0,
  area_name text not null,
  created_at timestamptz not null default now()
);
create unique index if not exists areas_city_page_name_uidx on public.areas (city, page_index, area_name);

-- Seed all values from JSON files
truncate table public.blog, public.locations, public.brands, public.contact, public.faq, public.metadata, public.service_details, public.services_commercial, public.services_residential, public.testimonials, public.why, public.areas restart identity;

insert into public.blog (id, slug, title, excerpt, category, "readTime", "publishedAt", image, content) values
  (1, 'why-refrigerator-not-cooling', 'Why Is My Refrigerator Not Cooling Properly?', 'Learn the most common causes behind warm fridge sections and what you can safely check before calling a technician.', 'Refrigerator', '4 min read', '2026-03-08', 'https://blog.keepe.com/content/images/2021/06/Image-53-01.png', 'A warm refrigerator is one of the most stressful kitchen emergencies. But before you panic and call a repair service, there are several things you can check yourself.

First, verify the thermostat settings. It sounds simple, but dials often get bumped. Next, check the condenser coils at the back or bottom of the fridge. If they are covered in dust, the refrigerator can''t cool efficiently.

"Regular maintenance is key to a long-lasting appliance."

If the coils are clean and the settings are correct, listen for the evaporator fan. If you don''t hear it running, or if it''s making a strange noise, it might be time to call a professional technician.'),
  (2, 'dryer-taking-too-long', 'Dryer Taking Too Long? 6 Fast Things to Inspect', 'From clogged vents to overloaded drums, these checks can improve drying performance and reduce energy bills.', 'Dryer', '5 min read', '2026-03-04', '/legacy/assets/rafixhero3.png', 'Waiting hours for a single load of laundry to dry is frustrating and wastes energy. A slow dryer is almost always a sign of restricted airflow.

Start by cleaning the lint screen thoroughly. Then, inspect the exterior vent hood to ensure it opens freely when the dryer is running. You should also check the flexible transition hose behind the dryer for kinks or heavy lint buildup.

"A clogged dryer vent is not just inefficient; it''s a serious fire hazard."

If the airflow is clear, the issue might be a faulty heating element or a cycling thermostat. In those cases, a certified technician can quickly diagnose and replace the broken parts.'),
  (3, 'dishwasher-not-cleaning', 'Dishwasher Not Cleaning Dishes? Start Here', 'A practical checklist for spray arms, filters, detergent use, and water temperature to fix poor cleaning results.', 'Dishwasher', '4 min read', '2026-02-27', '/legacy/assets/rafixhero3.png', 'Opening your dishwasher to find dirty, cloudy dishes defeats the purpose of having this appliance. Most cleaning issues stem from simple maintenance oversights.

The most common culprit is a clogged filter. Check the bottom of your tub and clean the filter assembly. Next, inspect the spray arms. Food particles can clog the small holes, preventing water from reaching your dishes.

"Hard water can cause mineral buildup, reducing your dishwasher''s effectiveness."

Ensure your water is hot enough (at least 120°F) and you''re using a high-quality detergent. If the problem persists, the circulation pump or an inlet valve might be failing.'),
  (4, 'washer-vibration-fix', 'How to Stop Washer Vibration and Noise', 'Simple leveling and load balancing tips that prevent excessive shaking and protect your machine from damage.', 'Washer', '3 min read', '2026-02-18', '/legacy/assets/rafixhero3.png', 'A washing machine that sounds like it''s taking off can be alarming and can damage both the machine and your floors.

The first step is checking if the machine is level. Use a bubble level and adjust the feet accordingly. Also, ensure you are not overloading the drum or washing a single heavy item without balancing the load.

"A balanced washer runs quieter and lasts significantly longer."

If the machine is level but still vibrates violently, the shock absorbers or suspension springs might be worn out. These parts degrade over time and require professional replacement to restore smooth operation.'),
  (5, 'oven-not-heating-evenly', 'Oven Not Heating Evenly? Common Causes', 'Find out when uneven cooking is caused by sensors, heating elements, or airflow and when professional repair is needed.', 'Oven', '6 min read', '2026-02-10', '/legacy/assets/rafixhero3.png', 'Uneven baking can ruin your favorite recipes. When half your cookies are burnt and the other half are raw, your oven needs attention.

If you have an electric oven, visibly inspect the bake element at the bottom. It should glow red evenly. If there are dark spots, it''s likely failing. For gas ovens, check the igniter; a weak igniter won''t open the gas valve correctly.

"Proper airflow is crucial for even heat distribution."

Oven temperature sensors can also drift over time. You can recalibrate the thermostat using an oven thermometer, but if the sensor is faulty, a replacement is the only way to ensure accurate cooking temperatures.'),
  (6, 'ice-machine-low-output', 'Ice Machine Producing Too Little Ice?', 'Check water supply, filters, condenser cleanliness, and temperature settings to restore ice production speed.', 'Ice Machine', '4 min read', '2026-02-03', '/legacy/assets/rafixhero3.png', 'A slow ice maker can put a damper on your summer parties. Ice production relies on steady water flow and freezing temperatures.

Verify that your freezer is set to 0°F (-18°C) or colder. If the freezer is too warm, ice production slows down drastically. Next, check the water filter. A clogged filter reduces water flow to the ice maker.

"Change your refrigerator water filter every 6 months for optimal ice speed."

If the temperature and filter are fine, inspect the condenser coils and ensure the water inlet valve isn''t restricted. For persistent issues, a technician can test the ice maker module itself.');

insert into public.locations (slug, name, region, description, "mapEmbedUrl", "subAreas") values
  ('houston', 'Houston', 'Houston, TX', 'Professional appliance repair services in Houston, TX. mperium Appliance provides same-day and next-day appliance repair across the Houston metro area with licensed technicians and 90-day warranty.', 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d443088.1302985258!2d-95.6834015!3d29.8168824!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x8640b8b4488d8501%3A0xca0d02def365053b!2sHouston%2C%20TX!5e0!3m2!1sen!2sus!4v1700000000000!5m2!1sen!2sus', '["Downtown Houston","Midtown","The Heights","Montrose","River Oaks","Memorial","Galleria","Energy Corridor","Bellaire","West University Place","Museum District","Rice Village"]'::jsonb),
  ('tomball', 'Tomball', 'Houston, TX', 'Expert appliance repair services in Tomball, TX. Fast, reliable repairs for all major brands with same-day availability and transparent pricing.', 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d55348.97!2d-95.64!3d30.097!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x8640d2bca9a8a8a1%3A0x3e3e3e3e3e3e3e3e!2sTomball%2C%20TX!5e0!3m2!1sen!2sus!4v1700000000000!5m2!1sen!2sus', '["Tomball Town Center","Lakewood Forest","Spring Creek Oaks","Northpointe","Creekside Park","Decker Prairie"]'::jsonb),
  ('spring', 'Spring', 'Houston, TX', 'Trusted appliance repair in Spring, TX. mperium Appliance technicians serve all neighborhoods in Spring with professional, same-day service and 90-day warranty on all repairs.', 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d55300!2d-95.42!3d30.08!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x8640d68ab0b01c3f%3A0x4e4e4e4e4e4e4e4e!2sSpring%2C%20TX!5e0!3m2!1sen!2sus!4v1700000000000!5m2!1sen!2sus', '["Old Town Spring","Spring Trails","Gleannloch Farms","Klein","Louetta","Champion Forest"]'::jsonb),
  ('katy', 'Katy', 'Houston, TX', 'Professional appliance repair services in Katy, TX. Quick response times, licensed technicians, and affordable pricing for all major appliance brands.', 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d55400!2d-95.82!3d29.79!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x8640dca739cb56e1%3A0x5a5a5a5a5a5a5a5a!2sKaty%2C%20TX!5e0!3m2!1sen!2sus!4v1700000000000!5m2!1sen!2sus', '["Cinco Ranch","Firethorne","Cross Creek Ranch","Elyson","Grand Lakes","Seven Meadows","Cane Island"]'::jsonb),
  ('humble', 'Humble', 'Houston, TX', 'Reliable appliance repair services in Humble, TX. Our certified technicians provide fast, quality repairs with transparent pricing and warranty coverage.', 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d55300!2d-95.26!3d29.99!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x8640b02a0aa5edcf%3A0x6a6a6a6a6a6a6a6a!2sHumble%2C%20TX!5e0!3m2!1sen!2sus!4v1700000000000!5m2!1sen!2sus', '["Kingwood","Fall Creek","Eagle Springs","Lakeshore","Summerwood","Atascocita"]'::jsonb),
  ('atascocita', 'Atascocita', 'Houston, TX', 'Quality appliance repair in Atascocita, TX. mperium Appliance offers same-day repair service for all major appliance brands with expert technicians.', 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d55300!2d-95.18!3d29.97!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x8640b4f38e6da5c5%3A0x7a7a7a7a7a7a7a7a!2sAtascocita%2C%20TX!5e0!3m2!1sen!2sus!4v1700000000000!5m2!1sen!2sus', '["Shadow Creek","Pinehurst","Walden","Lakeshore","Kings River","Woodland Hills"]'::jsonb),
  ('woodlands', 'Woodlands', 'Houston, TX', 'Premium appliance repair services in The Woodlands, TX. Licensed technicians, same-day appointments, and 90-day warranty on all repairs.', 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d55250!2d-95.51!3d30.17!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x8647330fd9a76b85%3A0x8a8a8a8a8a8a8a8a!2sThe%20Woodlands%2C%20TX!5e0!3m2!1sen!2sus!4v1700000000000!5m2!1sen!2sus', '["Creekside Park","Alden Bridge","Cochrans Crossing","Grogan''s Mill","Indian Springs","Panther Creek","Sterling Ridge"]'::jsonb),
  ('klein', 'Klein', 'Houston, TX', 'Reliable appliance repair in Klein, TX. Expert service for refrigerators, washers, dryers, dishwashers, and more with fast response times.', 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d55300!2d-95.55!3d30.00!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x8640d3d2a0a9a9a9%3A0x9a9a9a9a9a9a9a9a!2sKlein%2C%20TX!5e0!3m2!1sen!2sus!4v1700000000000!5m2!1sen!2sus', '["Klein Forest","Klein Oak","Champions","Willowbrook","Vintage Park","Champions Forest"]'::jsonb),
  ('new-caney', 'New Caney', 'Houston, TX', 'Professional appliance repair in New Caney, TX. Quick, affordable repairs for all major brands with certified technicians.', 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d55300!2d-95.23!3d30.15!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x864735aaa1a1a1a1%3A0xaaaaaaaaaaaaaaaa!2sNew%20Caney%2C%20TX!5e0!3m2!1sen!2sus!4v1700000000000!5m2!1sen!2sus', '["River Plantation","Valley Ranch","Tavola","Kings Manor","Roman Forest"]'::jsonb),
  ('magnolia', 'Magnolia', 'Houston, TX', 'Trusted appliance repair in Magnolia, TX. mperium Appliance provides expert repairs for all major brands with same-day service availability.', 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d55300!2d-95.75!3d30.21!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x864738b1b1b1b1b1%3A0xbbbbbbbbbbbbbbbb!2sMagnolia%2C%20TX!5e0!3m2!1sen!2sus!4v1700000000000!5m2!1sen!2sus', '["Mostyn Manor","High Meadow Ranch","Magnolia Ridge","Dobbin","Todd Mission"]'::jsonb),
  ('grangerland', 'Grangerland', 'Houston, TX', 'Dependable appliance repair services in Grangerland, TX. Licensed technicians with same-day availability and quality-guaranteed repairs.', 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d55250!2d-95.49!3d30.34!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x864739c1c1c1c1c1%3A0xcccccccccccccccc!2sGrangerland%2C%20TX!5e0!3m2!1sen!2sus!4v1700000000000!5m2!1sen!2sus', '["Grangerland Village","Cedar Point","Pine Shadows","White Oak Estates"]'::jsonb),
  ('conroe', 'Conroe', 'Houston, TX', 'Expert appliance repair in Conroe, TX. mperium Appliance delivers fast, professional repairs for refrigerators, washers, dryers, ovens, and more.', 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d55200!2d-95.46!3d30.31!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x86473a0d0d0d0d0d%3A0xdddddddddddddddd!2sConroe%2C%20TX!5e0!3m2!1sen!2sus!4v1700000000000!5m2!1sen!2sus', '["Grand Central Park","April Sound","Lake Conroe","River Plantation","Conroe Town Center"]'::jsonb),
  ('montgomery', 'Montgomery', 'Houston, TX', 'Quality appliance repair services in Montgomery, TX. Transparent pricing, certified technicians, and comprehensive warranty coverage.', 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d55200!2d-95.69!3d30.39!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x86473be1e1e1e1e1%3A0xeeeeeeeeeeeeeeee!2sMontgomery%2C%20TX!5e0!3m2!1sen!2sus!4v1700000000000!5m2!1sen!2sus', '["Bentwater","Walden on Lake Conroe","La Torretta","Legends Trail","Montgomery Town Center"]'::jsonb),
  ('austin', 'Austin', 'Austin, TX', 'Professional appliance repair services in Austin, TX. mperium Appliance provides same-day and next-day repairs across the Austin metro area with licensed technicians.', 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d441400.7551391056!2d-97.9222068!3d30.3074624!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x8644b599a0cc032f%3A0x5d9b464bd469d57a!2sAustin%2C%20TX!5e0!3m2!1sen!2sus!4v1700000000000!5m2!1sen!2sus', '["Downtown Austin","South Congress","East Austin","Zilker","Barton Hills","Hyde Park","Mueller","Domain","Westlake Hills","Tarrytown"]'::jsonb),
  ('bee-cave', 'Bee Cave', 'Austin, TX', 'Expert appliance repair in Bee Cave, TX. Fast, reliable service for all major brands with same-day availability and transparent pricing.', 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d55300!2d-97.95!3d30.31!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x865b4a0f0f0f0f0f%3A0xf0f0f0f0f0f0f0f0!2sBee%20Cave%2C%20TX!5e0!3m2!1sen!2sus!4v1700000000000!5m2!1sen!2sus', '["Falconhead","Lake Pointe","Spanish Oaks","Homestead","Shops at the Galleria"]'::jsonb),
  ('briarcliff', 'Briarcliff', 'Austin, TX', 'Dependable appliance repair in Briarcliff, TX. Professional technicians providing quality repairs for all major appliance brands.', 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d55300!2d-97.89!3d30.40!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x865b4b1a1a1a1a1a%3A0xa1a1a1a1a1a1a1a1!2sBriarcliff%2C%20TX!5e0!3m2!1sen!2sus!4v1700000000000!5m2!1sen!2sus', '["Briarcliff Marina","Lago Vista Highlands","Lake Travis Estates"]'::jsonb),
  ('brushy-creek', 'Brushy Creek', 'Austin, TX', 'Trusted appliance repair in Brushy Creek, TX. mperium Appliance delivers same-day repairs with certified technicians and 90-day warranty.', 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d55300!2d-97.73!3d30.51!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x865b2c2b2b2b2b2b%3A0xb2b2b2b2b2b2b2b2!2sBrushy%20Creek%2C%20TX!5e0!3m2!1sen!2sus!4v1700000000000!5m2!1sen!2sus', '["Brushy Creek Village","Sendero Springs","Ranch at Brushy Creek","Fern Bluff"]'::jsonb),
  ('cedar-park', 'Cedar Park', 'Austin, TX', 'Professional appliance repair services in Cedar Park, TX. Fast response times, expert technicians, and affordable pricing for all major brands.', 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d55300!2d-97.82!3d30.51!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x865b2d3c3c3c3c3c%3A0xc3c3c3c3c3c3c3c3!2sCedar%20Park%2C%20TX!5e0!3m2!1sen!2sus!4v1700000000000!5m2!1sen!2sus', '["Twin Creeks","Buttercup Creek","Carriage Hills","Anderson Mill","Cypress Canyon","Ranch at Brushy Creek"]'::jsonb),
  ('georgetown', 'Georgetown', 'Austin, TX', 'Expert appliance repair in Georgetown, TX. mperium Appliance provides fast, reliable repairs for all major brands across Georgetown and surrounding neighborhoods.', 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d55150!2d-97.68!3d30.63!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x8644d7e0c0c0c0c1%3A0xd4d4d4d4d4d4d4d4!2sGeorgetown%2C%20TX!5e0!3m2!1sen!2sus!4v1700000000000!5m2!1sen!2sus', '["Sun City Texas","Wolf Ranch","Rancho Sienna","Berry Creek","Teravista","Parkside at Mayfield Ranch","The Oaks at San Gabriel","Cimarron Hills","MorningStar","La Conterra","Estates of Westlake","Old Town / Historic Downtown Georgetown","Reata Trails","Serenada","Georgetown Village"]'::jsonb),
  ('hudson-bend', 'Hudson Bend', 'Austin, TX', 'Reliable appliance repair in Hudson Bend, TX. Quality repairs for all major appliance brands with licensed technicians.', 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d55300!2d-97.92!3d30.39!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x865b4e5e5e5e5e5e%3A0xe5e5e5e5e5e5e5e5!2sHudson%20Bend%2C%20TX!5e0!3m2!1sen!2sus!4v1700000000000!5m2!1sen!2sus', '["Steiner Ranch","River Place","Lake Travis Estates","Comanche Trail"]'::jsonb),
  ('hutto', 'Hutto', 'Austin, TX', 'Professional appliance repair in Hutto, TX. Same-day service, transparent pricing, and certified technicians for all major brands.', 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d55250!2d-97.55!3d30.54!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x8644d16f6f6f6f6f%3A0xf6f6f6f6f6f6f6f6!2sHutto%2C%20TX!5e0!3m2!1sen!2sus!4v1700000000000!5m2!1sen!2sus', '["Star Ranch","Riverwalk","Emory Farms","Hutto Town Center","Creek Bend"]'::jsonb),
  ('jonestown', 'Jonestown', 'Austin, TX', 'Trusted appliance repair in Jonestown, TX. mperium Appliance provides fast, affordable repairs with expert technicians and warranty coverage.', 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d55250!2d-97.92!3d30.49!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x865b3a7a7a7a7a7a%3A0xa7a7a7a7a7a7a7a7!2sJonestown%2C%20TX!5e0!3m2!1sen!2sus!4v1700000000000!5m2!1sen!2sus', '["Jones Brothers Park","Lago Vista Area","Shady Hollow","North Shore"]'::jsonb),
  ('lago-vista', 'Lago Vista', 'Austin, TX', 'Quality appliance repair in Lago Vista, TX. Professional service for all major appliance brands with same-day availability.', 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d55250!2d-97.98!3d30.46!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x865b3b8b8b8b8b8b%3A0xb8b8b8b8b8b8b8b8!2sLago%20Vista%2C%20TX!5e0!3m2!1sen!2sus!4v1700000000000!5m2!1sen!2sus', '["Highland Lake Estates","Bar K Ranches","Balcones Canyonlands","Point Venture"]'::jsonb),
  ('lakeway', 'Lakeway', 'Austin, TX', 'Premium appliance repair in Lakeway, TX. Expert technicians, fast service, and transparent pricing for all appliance brands.', 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d55300!2d-97.97!3d30.36!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x865b4c9c9c9c9c9c%3A0xc9c9c9c9c9c9c9c9!2sLakeway%2C%20TX!5e0!3m2!1sen!2sus!4v1700000000000!5m2!1sen!2sus', '["Lakeway Highlands","Rough Hollow","The Hills","Flintrock Falls","Serene Hills"]'::jsonb),
  ('leander', 'Leander', 'Austin, TX', 'Reliable appliance repair in Leander, TX. mperium Appliance delivers same-day service with licensed technicians and quality-guaranteed repairs.', 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d55250!2d-97.85!3d30.58!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x865b2adadadadada%3A0xdadadadadadadada!2sLeander%2C%20TX!5e0!3m2!1sen!2sus!4v1700000000000!5m2!1sen!2sus', '["Crystal Falls","Travisso","Mason Hills","Cold Springs","Sarita Valley","Bryson"]'::jsonb),
  ('pflugerville', 'Pflugerville', 'Austin, TX', 'Expert appliance repair in Pflugerville, TX. Fast, affordable repairs for refrigerators, washers, dryers, and more with certified technicians.', 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d55300!2d-97.62!3d30.44!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x8644c8ebebebebeb%3A0xebebebebebebebeb!2sPflugerville%2C%20TX!5e0!3m2!1sen!2sus!4v1700000000000!5m2!1sen!2sus', '["Blackhawk","Falcon Pointe","Highland Park","Meadows of Blackhawk","Avalon","Stone Hill Town Center"]'::jsonb),
  ('point-venture', 'Point Venture', 'Austin, TX', 'Trusted appliance repair in Point Venture, TX. Professional service with transparent pricing and 90-day warranty on all repairs.', 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d55250!2d-97.95!3d30.41!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x865b3cfcfcfcfcfc%3A0xfcfcfcfcfcfcfcfc!2sPoint%20Venture%2C%20TX!5e0!3m2!1sen!2sus!4v1700000000000!5m2!1sen!2sus', '["Point Venture Lakefront","Lago Vista Shores","North Lake Travis"]'::jsonb);

insert into public.brands (slug, title, description, image, premium) values
  ('1', 'Bosch Appliance Repair - mperium Appliance', 'Professional appliance repair services. Same-day service, 90-day warranty, licensed technicians.', '/legacy/assets/20260218002904533_dccd50a9-08d4-48aa-a8b9-15dab143dc7d.jpg', false),
  ('2', 'Whirlpool Appliance Repair - mperium Appliance', 'Professional appliance repair services. Same-day service, 90-day warranty, licensed technicians.', '/legacy/assets/20260219113540085_de85eb0c-b81b-426a-ad28-fdeafc9a761f.png', false),
  ('3', 'Kenmore Appliance Repair - mperium Appliance', 'Professional appliance repair services. Same-day service, 90-day warranty, licensed technicians.', '/legacy/assets/20260219113609200_2fb035c7-a746-4168-99b2-b8275f503788.webp', false),
  ('4', 'Maytag Appliance Repair - mperium Appliance', 'Professional appliance repair services. Same-day service, 90-day warranty, licensed technicians.', '/legacy/assets/20260219113629379_567a4459-7ea4-4510-8882-19c199113e62.webp', false),
  ('5', 'Frigidaire Appliance Repair - mperium Appliance', 'Professional appliance repair services. Same-day service, 90-day warranty, licensed technicians.', '/legacy/assets/20260219113639417_4c98e2c0-9bdf-44df-a77c-ba1c1b925c6b.webp', false),
  ('6', 'Electrolux Appliance Repair - mperium Appliance', 'Professional appliance repair services. Same-day service, 90-day warranty, licensed technicians.', '/legacy/assets/20260219113650949_9117c0ba-17db-4b9b-8db3-e60ab7419862.png', false),
  ('7', 'Miele Appliance Repair - mperium Appliance', 'Professional appliance repair services. Same-day service, 90-day warranty, licensed technicians.', '/legacy/assets/20260219113703127_85f7e5f4-33f5-4202-b179-a3d4ae8e58fb.webp', false),
  ('8', 'Samsung Appliance Repair - mperium Appliance', 'Professional appliance repair services. Same-day service, 90-day warranty, licensed technicians.', '/legacy/assets/20260219113709840_b4e05997-39c8-4407-9e17-06e779d9818f.png', false),
  ('9', 'Viking Appliance Repair - mperium Appliance', 'Professional appliance repair services. Same-day service, 90-day warranty, licensed technicians.', '/legacy/assets/20260219113717309_1b986d9c-1744-4a54-ae9b-7ee0400b3172.webp', false),
  ('sub-zero', 'Sub-Zero Appliance Repair - mperium Appliance', 'Expert repair services for Sub-Zero luxury appliances. Same-day service, licensed technicians.', '/legacy/assets/20260218002904533_dccd50a9-08d4-48aa-a8b9-15dab143dc7d.jpg', true),
  ('thermador', 'Thermador Appliance Repair - mperium Appliance', 'Expert repair services for Thermador luxury appliances. Same-day service, licensed technicians.', '/legacy/assets/20260219113540085_de85eb0c-b81b-426a-ad28-fdeafc9a761f.png', true),
  ('viking', 'Viking Premium Appliance Repair - mperium Appliance', 'Professional repair services for Viking premium appliances. Same-day service, licensed technicians.', '/legacy/assets/20260219113717309_1b986d9c-1744-4a54-ae9b-7ee0400b3172.webp', true),
  ('wolf', 'Wolf Appliance Repair - mperium Appliance', 'Expert repair services for Wolf luxury appliances. Same-day service, licensed technicians.', '/legacy/assets/20260219113609200_2fb035c7-a746-4168-99b2-b8275f503788.webp', true),
  ('monogram', 'Monogram Appliance Repair - mperium Appliance', 'Professional repair services for Monogram luxury appliances. Same-day service, licensed technicians.', '/legacy/assets/20260219113629379_567a4459-7ea4-4510-8882-19c199113e62.webp', true);

insert into public.contact (phone, "phoneHref", email, location, "socialMedia", reviews) values ('(347) 791-1731', 'tel:3477911731', 'rafixappliancerepair@gmail.com', 'Austin TX & Houston TX', '[{"platform":"Instagram","href":"https://instagram.com/rafixapplianceservice"},{"platform":"YouTube","href":"https://www.youtube.com/@RafixApplianceRepair"}]'::jsonb, '{"count":"217","average":"4.9"}'::jsonb);

insert into public.faq (question, answer) values
  ('Do you offer same-day appliance repair?', 'Yes. We offer same-day appointments when slots are available. Call early for the fastest scheduling.'),
  ('Is there a service call fee?', 'We provide a free service call with completed repair. Our technician will diagnose the issue first and explain all costs before starting work.'),
  ('What brands and appliances do you repair?', 'We repair most major household and commercial appliances, including refrigerators, washers, dryers, dishwashers, ovens, ranges, cooktops, and more.'),
  ('Do your repairs come with a warranty?', 'Yes. All qualifying repairs are backed by our 90-day warranty on parts and labor.'),
  ('How long does a typical repair take?', 'Many issues are fixed on the first visit. If a special part is needed, we order it quickly and return as soon as it arrives.'),
  ('Which areas do you serve?', 'We serve the greater Houston and Austin areas. Contact us with your ZIP code and we will confirm coverage right away.');

insert into public.metadata (title, description, keywords) values ('mperium Appliance', 'Professional appliance repair services. Same-day service, 90-day warranty, licensed technicians.', 'appliance repair, repair services');

insert into public.service_details (slug, title, description, image) values
  ('1', 'Refrigerator Repair Services - mperium Appliance', 'Professional appliance repair services. Same-day service, 90-day warranty, licensed technicians.', null),
  ('2', 'Refrigerator Repair Services - mperium Appliance', 'Professional appliance repair services. Same-day service, 90-day warranty, licensed technicians.', null),
  ('3', 'Washer Repair Services - mperium Appliance', 'Professional appliance repair services. Same-day service, 90-day warranty, licensed technicians.', null),
  ('4', 'Ice Machine Repair Services - mperium Appliance', 'Professional appliance repair services. Same-day service, 90-day warranty, licensed technicians.', null),
  ('5', 'Dryer Repair Services - mperium Appliance', 'Professional appliance repair services. Same-day service, 90-day warranty, licensed technicians.', null),
  ('6', 'Dishwasher Repair Services - mperium Appliance', 'Professional appliance repair services. Same-day service, 90-day warranty, licensed technicians.', null),
  ('7', 'Oven Repair Services - mperium Appliance', 'Professional appliance repair services. Same-day service, 90-day warranty, licensed technicians.', null),
  ('8', 'Cooktop Repair Services - mperium Appliance', 'Professional appliance repair services. Same-day service, 90-day warranty, licensed technicians.', null),
  ('9', 'Microwave Repair Services - mperium Appliance', 'Professional appliance repair services. Same-day service, 90-day warranty, licensed technicians.', null),
  ('10', 'Wine Cooler Repair Services - mperium Appliance', 'Professional appliance repair services. Same-day service, 90-day warranty, licensed technicians.', null),
  ('11', 'Freezer Repair Services - mperium Appliance', 'Professional appliance repair services. Same-day service, 90-day warranty, licensed technicians.', null),
  ('12', 'Garbage Disposal Repair Services - mperium Appliance', 'Professional appliance repair services. Same-day service, 90-day warranty, licensed technicians.', null),
  ('13', 'Stove Repair Services - mperium Appliance', 'Professional appliance repair services. Same-day service, 90-day warranty, licensed technicians.', null),
  ('14', 'Range Repair Services - mperium Appliance', 'Professional appliance repair services. Same-day service, 90-day warranty, licensed technicians.', null),
  ('15', 'Washer Repair Services - mperium Appliance', 'Professional appliance repair services. Same-day service, 90-day warranty, licensed technicians.', null),
  ('16', 'Ice Machine Repair Services - mperium Appliance', 'Professional appliance repair services. Same-day service, 90-day warranty, licensed technicians.', null),
  ('17', 'Dryer Repair Services - mperium Appliance', 'Professional appliance repair services. Same-day service, 90-day warranty, licensed technicians.', null),
  ('18', 'Dishwasher Repair Services - mperium Appliance', 'Professional appliance repair services. Same-day service, 90-day warranty, licensed technicians.', null),
  ('19', 'Oven Repair Services - mperium Appliance', 'Professional appliance repair services. Same-day service, 90-day warranty, licensed technicians.', null),
  ('20', 'Cooktop Repair Services - mperium Appliance', 'Professional appliance repair services. Same-day service, 90-day warranty, licensed technicians.', null),
  ('21', 'Microwave Repair Services - mperium Appliance', 'Professional appliance repair services. Same-day service, 90-day warranty, licensed technicians.', null),
  ('22', 'Wine Cooler Repair Services - mperium Appliance', 'Professional appliance repair services. Same-day service, 90-day warranty, licensed technicians.', null),
  ('23', 'Freezer Repair Services - mperium Appliance', 'Professional appliance repair services. Same-day service, 90-day warranty, licensed technicians.', null),
  ('24', 'Stove Repair Services - mperium Appliance', 'Professional appliance repair services. Same-day service, 90-day warranty, licensed technicians.', null),
  ('25', 'Garbage Disposal Repair Services - mperium Appliance', 'Professional appliance repair services. Same-day service, 90-day warranty, licensed technicians.', null),
  ('26', 'Vent Hood Repair Services - mperium Appliance', 'Professional appliance repair services. Same-day service, 90-day warranty, licensed technicians.', null),
  ('27', 'Range Repair Services - mperium Appliance', 'Professional appliance repair services. Same-day service, 90-day warranty, licensed technicians.', null);

insert into public.services_commercial (title, description, href, icon) values
  ('Refrigerator', 'Inconsistent temperatures, compressor failures & excessive energy consumption', '/services/1', '/legacy/assets/20260217235329971_dd0384d5-d100-4a1d-9884-3feaa2cebe0f.svg'),
  ('Washer', 'Failure to fill, excessive vibration & cycle interruptions', '/services/15', '/legacy/assets/20260223063515182_234e5652-dc18-46de-9cec-cea284f26c92.svg'),
  ('Ice Machine', 'Slow ice production, machine cycling issues & water line blockages', '/services/16', '/legacy/assets/20260223063837481_66fcf88e-2721-44a6-989c-1ff24ec4d217.png'),
  ('Dryer', 'Extended drying times, overheating & drum not turning', '/services/17', '/legacy/assets/20260223064146334_f24c11ea-8173-476e-b3cc-c3a522badb5d.svg'),
  ('Dishwasher', 'Poor wash cycles, water temperature failures & drainage clogs', '/services/18', '/legacy/assets/20260223070143127_36a591cc-b131-4c0f-902b-c00b9314df7a.svg'),
  ('Oven', 'Inconsistent baking temperatures, door seal failures & control board errors', '/services/19', '/legacy/assets/20260223070734108_b7c045eb-9b20-49a5-9087-1d841ca622c5.svg'),
  ('Cooktop', 'Burner malfunctions, ignition delays & surface damage', '/services/20', '/legacy/assets/20260223071026936_c5bd7558-6d48-4b4a-972f-f0eae8075a7b.svg'),
  ('Microwave', 'No heat output, door latch failures & power inconsistencies', '/services/21', '/legacy/assets/20260223071201706_fd5afa83-7a9d-4f61-ad10-9be3f1ebabd9.svg'),
  ('Wine Cooler', 'Uneven zone temperatures, condenser failures & humidity issues', '/services/22', '/legacy/assets/20260223071339519_967106f4-b28a-477b-881c-3060164d24e7.png'),
  ('Freezer', 'Temperature fluctuations, ice buildup & compressor cycling issues', '/services/23', '/legacy/assets/20260223071822984_ca95f9ce-4853-41aa-99ef-3d6f3779c48b.svg'),
  ('Stove', 'Ignition problems, inconsistent flame & burner blockages', '/services/24', '/legacy/assets/20260223072153883_e71027bf-ce13-49b7-b171-9343d994582a.svg'),
  ('Garbage Disposal', 'Frequent jams, slow grinding & motor burnout', '/services/25', '/legacy/assets/20260223072251245_4194d52a-13c9-460c-8637-b64b5c6232b9.png'),
  ('Vent Hood', 'Poor ventilation, motor failures & grease buildup', '/services/26', '/legacy/assets/20260223072609109_6ee40a13-973c-4cd2-bd35-5ce04c4c6e42.svg'),
  ('Range', 'Pilot light failures, uneven heating & gas line issues', '/services/27', '/legacy/assets/20260223072844119_db47f1ab-4ea1-4d8d-adff-c1e774b83326.svg');

insert into public.services_residential (title, description, href, icon) values
  ('Refrigerator', 'Cooling issues, leaks & compressor repairs', '/services/2', '/legacy/assets/20260217235424768_e2f99286-ed0b-4bb7-a681-9955bc2734d1.svg'),
  ('Washer', 'Won''t spin, drain issues & excessive vibration', '/services/3', '/legacy/assets/20260218183711838_2b0e132c-01eb-4d5a-9167-6a28eb05b8ed.svg'),
  ('Ice Machine', 'Low ice production, leaks & freezing malfunctions', '/services/4', '/legacy/assets/20260220111650311_bd1ad6a3-f10b-40a9-b579-db8b48cc1a94.png'),
  ('Dryer', 'No heat, long drying times & unusual noises', '/services/5', '/legacy/assets/20260220112112571_743fa510-8bc4-4e43-bf1d-b77fd7cb7124.svg'),
  ('Dishwasher', 'Not cleaning properly, water leaks & drainage problems', '/services/6', '/legacy/assets/20260220112239961_9ed80573-d0ff-4960-b932-02e80c6b9ff0.svg'),
  ('Oven', 'Uneven heating, temperature fluctuations & ignition failures', '/services/7', '/legacy/assets/20260220112353698_d8c1e3c4-ff25-49dc-b4ec-8318c91da6ab.svg'),
  ('Cooktop', 'Burners not lighting, inconsistent flame & cracked surfaces', '/services/8', '/legacy/assets/20260220112440166_6ac4f480-8182-49fa-84f1-a17b2b5a465e.svg'),
  ('Microwave', 'Not heating, sparking & turntable malfunctions', '/services/9', '/legacy/assets/20260220112527026_0ea73a83-9144-47b7-bf0b-30324ed5b36d.svg'),
  ('Wine Cooler', 'Temperature inconsistencies, compressor noise & condensation buildup', '/services/10', '/legacy/assets/20260220112634038_e15d7135-1cc2-40d7-9cb6-4df3610b5242.png'),
  ('Freezer', 'Not freezing, frost buildup & unusual noises', '/services/11', '/legacy/assets/20260220112732827_57e14d9f-c6de-4834-89f4-6ffee6843183.svg'),
  ('Garbage Disposal', 'Jammed blades, leaks & motor humming without grinding', '/services/12', '/legacy/assets/20260220112851535_484a35c5-afeb-409e-831c-e0b7b2b980c6.png'),
  ('Stove', 'Burners not heating, gas smell & faulty temperature control', '/services/13', '/legacy/assets/20260220113048023_fe8d955f-557c-438e-9c85-4f6136fece33.png'),
  ('Range', 'Uneven cooking, burner failures & self-clean malfunctions', '/services/14', '/legacy/assets/20260220113241155_1f5d686e-b6c7-4040-8968-c26484fade0c.svg');

insert into public.testimonials (initials, name, location, text, avatar) values
  ('KK', 'Kat', 'Austin', '"Very good service and completely honest recommendations with transparent fair pricing. Definitely recommend this company for your appliance repair needs."', null),
  ('LH', 'Lashawn Henderson', 'Austin', '"I was having a problem with my refrigerator cooling and Roma fixed it!!! He was on time, fast and had great customer service... I highly recommend mperium Appliance!!"', null),
  ('RR', 'Rick Roemer', 'Houston', '"Excellent work! Honest. On time. Friendly. Got my washer working again!"', null),
  ('DL', 'Daniel Luque', 'Austin', '"Repaired my dryer very quickly and effectively! Was able to come the very next day so I appreciate that and even cleaned up the laundry closet which was totally unnecessary. Highly recommend!"', null),
  ('JB', 'Jessica Buchanan', 'Austin', '"Excellent experience! He responded quickly, showed up on time, and repaired our microwave efficiently. He explained everything clearly and was very professional. I would definitely use him again."', null),
  ('KA', 'Karen Anderson', 'Houston, TX', '"Great service!  Came early and fixed stove. Explaining everything,  highly recommended!!"', null),
  ('RL', 'Robbye Lewis', 'Houston, TX', '"Roma doesn’t did an excellent job! He fixed my dryer quickly and explained everything in detail! The price was fair and let me know the cost before he started! Definitely Recommend!!"', null),
  ('VM', 'Vanessa M', 'Houston, TX', '"Roma was awesome, came by quotes a price and was able to order replacement part and fix in less than a week, also was very thorough and identified another part that also needed replacing. Would highly recommend."', null),
  ('oo', 'osas obaseki', 'Houston, TX', '"They responded to my call quickly, arrived on time and the guy for sure knew his stuff and was very professional. They ordered the broken part and just like that I was back cooking. Overall I highly recommend them"', null),
  ('MM', 'Melinda Myers', 'Houston, TX', '"The technician was very thorough and explained things and the price was reasonable. When we ordered the part didn’t take long for him to come back to install. I would recommend this company."', null),
  (null, 'Treasure Dimalanta', 'Houston, TX', '"very satisfied with the work and timing. he came in assessed the problem, ordered parts quickly, and returned to finish the job. even took the time to make sure the water came out clean and the filter was working."', '/legacy/assets/20260219154000673_691e71e2-e918-4cea-804d-9a1cd3e8c0be.png');

insert into public.why (title, description, icon) values
  ('Same-Day Service', 'We arrive when you need us, often within hours.', '<svg fill="none" height="24" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24" width="24" xmlns="http://www.w3.org/2000/svg"><circle cx="12" cy="12" r="10" /><polyline points="12 6 12 12 16 14" /></svg>'),
  ('Certified Technicians', 'Factory-trained experts for all major brands.', '<svg fill="none" height="24" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24" width="24" xmlns="http://www.w3.org/2000/svg"><circle cx="12" cy="8" r="7" /><polyline points="8.21 13.89 7 23 12 20 17 23 15.79 13.88" /></svg>'),
  ('Upfront Pricing', 'Flat-rate pricing. No surprises on your bill.', '<svg fill="none" height="24" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24" width="24" xmlns="http://www.w3.org/2000/svg"><line x1="12" x2="12" y1="1" y2="23" /><path d="M17 5H9.5a3.5 3.5 0 0 0 0 7h5a3.5 3.5 0 0 1 0 7H6" /></svg>'),
  ('90-Day Warranty', 'We stand behind our parts and labor.', '<svg fill="none" height="24" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24" width="24" xmlns="http://www.w3.org/2000/svg"><path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z" /><path d="m9 12 2 2 4-4" /></svg>');

insert into public.areas (city, page_index, area_name) values
  ('houston', 0, 'Houston'),
  ('houston', 0, 'Tomball'),
  ('houston', 0, 'Spring'),
  ('houston', 0, 'Katy'),
  ('houston', 0, 'Humble'),
  ('houston', 0, 'Atascocita'),
  ('houston', 0, 'Woodlands'),
  ('houston', 0, 'Klein'),
  ('houston', 1, 'New Caney'),
  ('houston', 1, 'Magnolia'),
  ('houston', 1, 'Grangerland'),
  ('houston', 1, 'Conroe'),
  ('houston', 1, 'Montgomery'),
  ('austin', 0, 'Austin'),
  ('austin', 0, 'Bee Cave'),
  ('austin', 0, 'Briarcliff'),
  ('austin', 0, 'Brushy Creek'),
  ('austin', 0, 'Cedar Park'),
  ('austin', 0, 'Georgetown'),
  ('austin', 0, 'Hudson Bend'),
  ('austin', 0, 'Hutto'),
  ('austin', 1, 'Jonestown'),
  ('austin', 1, 'Lago Vista'),
  ('austin', 1, 'Lakeway'),
  ('austin', 1, 'Leander'),
  ('austin', 1, 'Pflugerville'),
  ('austin', 1, 'Point Venture');

-- Default RLS (public read)
do $$
declare
  table_name text;
  table_names text[] := array[
    'contact',
    'blog',
    'services_residential',
    'services_commercial',
    'testimonials',
    'why',
    'areas',
    'locations',
    'faq',
    'brands',
    'metadata',
    'service_details'
  ];
begin
  foreach table_name in array table_names
  loop
    execute format('alter table public.%I enable row level security', table_name);

    if not exists (
      select 1
      from pg_policies
      where schemaname = 'public'
        and tablename = table_name
        and policyname = 'public_read'
    ) then
      execute format(
        'create policy public_read on public.%I for select using (true)',
        table_name
      );
    end if;
  end loop;
end
$$;
