const fs = require('fs');
const path = require('path');

const root = process.cwd();
const dataDir = path.join(root, 'data');
const outFile = path.join(root, 'supabase', 'schema.sql');

function readJson(name) {
  return JSON.parse(fs.readFileSync(path.join(dataDir, name), 'utf8'));
}

function sqlString(value) {
  if (value === null || value === undefined) return 'null';
  return `'${String(value).replace(/'/g, "''")}'`;
}

function sqlJson(value) {
  const raw = JSON.stringify(value).replace(/'/g, "''");
  return `'${raw}'::jsonb`;
}

const blog = readJson('blog.json');
const locations = readJson('locations.json');
const brands = readJson('brands.json');
const contact = readJson('contact.json');
const faq = readJson('faq.json');
const metadata = readJson('metadata.json');
const serviceDetails = readJson('service-details.json');
const servicesCommercial = readJson('services-commercial.json');
const servicesResidential = readJson('services-residential.json');
const testimonials = readJson('testimonials.json');
const why = readJson('why.json');
const areas = readJson('areas.json');

const lines = [];

lines.push('-- Supabase Schema for RAFIX Appliance Repair');
lines.push('-- Auto-generated from data/*.json');
lines.push('');
lines.push('-- 1) blog.json -> blog');
lines.push('create table if not exists public.blog (');
lines.push('  id bigint primary key,');
lines.push('  slug text unique not null,');
lines.push('  title text not null,');
lines.push('  excerpt text,');
lines.push('  category text,');
lines.push('  "readTime" text,');
lines.push('  "publishedAt" text,');
lines.push('  image text,');
lines.push('  content text');
lines.push(');');
lines.push('');
lines.push('-- 2) locations.json -> locations');
lines.push('create table if not exists public.locations (');
lines.push('  slug text primary key,');
lines.push('  name text not null,');
lines.push('  region text,');
lines.push('  description text,');
lines.push('  "mapEmbedUrl" text,');
lines.push("  \"subAreas\" jsonb default '[]'::jsonb");
lines.push(');');
lines.push('');
lines.push('-- 3) brands.json -> brands');
lines.push('create table if not exists public.brands (');
lines.push('  slug text primary key,');
lines.push('  title text not null,');
lines.push('  description text,');
lines.push('  image text,');
lines.push('  premium boolean default false');
lines.push(');');
lines.push('');
lines.push('-- 4) contact.json -> contact');
lines.push('create table if not exists public.contact (');
lines.push('  id bigint generated by default as identity primary key,');
lines.push('  phone text,');
lines.push('  "phoneHref" text,');
lines.push('  email text,');
lines.push('  location text,');
lines.push("  \"socialMedia\" jsonb default '[]'::jsonb,");
lines.push("  reviews jsonb default '{}'::jsonb");
lines.push(');');
lines.push('');
lines.push('-- 5) faq.json -> faq');
lines.push('create table if not exists public.faq (');
lines.push('  id bigint generated by default as identity primary key,');
lines.push('  question text not null,');
lines.push('  answer text not null');
lines.push(');');
lines.push('create unique index if not exists faq_question_uidx on public.faq (question);');
lines.push('');
lines.push('-- 6) metadata.json -> metadata');
lines.push('create table if not exists public.metadata (');
lines.push('  id bigint generated by default as identity primary key,');
lines.push('  title text not null,');
lines.push('  description text,');
lines.push('  keywords text');
lines.push(');');
lines.push('');
lines.push('-- 7) service-details.json -> service_details');
lines.push('create table if not exists public.service_details (');
lines.push('  slug text primary key,');
lines.push('  title text not null,');
lines.push('  description text,');
lines.push('  image text');
lines.push(');');
lines.push('');
lines.push('-- 8) services-commercial.json -> services_commercial');
lines.push('create table if not exists public.services_commercial (');
lines.push('  id bigint generated by default as identity primary key,');
lines.push('  title text not null,');
lines.push('  description text,');
lines.push('  href text,');
lines.push('  icon text');
lines.push(');');
lines.push('');
lines.push('-- 9) services-residential.json -> services_residential');
lines.push('create table if not exists public.services_residential (');
lines.push('  id bigint generated by default as identity primary key,');
lines.push('  title text not null,');
lines.push('  description text,');
lines.push('  href text,');
lines.push('  icon text');
lines.push(');');
lines.push('');
lines.push('-- 10) testimonials.json -> testimonials');
lines.push('create table if not exists public.testimonials (');
lines.push('  id bigint generated by default as identity primary key,');
lines.push('  initials text,');
lines.push('  name text not null,');
lines.push('  location text,');
lines.push('  text text not null,');
lines.push('  avatar text');
lines.push(');');
lines.push('');
lines.push('-- 11) why.json -> why');
lines.push('create table if not exists public.why (');
lines.push('  id bigint generated by default as identity primary key,');
lines.push("  features jsonb default '[]'::jsonb,");
lines.push("  stats jsonb default '[]'::jsonb");
lines.push(');');
lines.push('');
lines.push('-- 12) areas.json -> areas');
lines.push('create table if not exists public.areas (');
lines.push('  id bigint generated by default as identity primary key,');
lines.push('  city text not null,');
lines.push('  page_index integer not null default 0,');
lines.push('  area_name text not null,');
lines.push('  created_at timestamptz not null default now()');
lines.push(');');
lines.push('create unique index if not exists areas_city_page_name_uidx on public.areas (city, page_index, area_name);');
lines.push('');

lines.push('-- Seed all values from JSON files');
lines.push('truncate table public.blog, public.locations, public.brands, public.contact, public.faq, public.metadata, public.service_details, public.services_commercial, public.services_residential, public.testimonials, public.why, public.areas restart identity;');
lines.push('');

if (blog.length) {
  lines.push('insert into public.blog (id, slug, title, excerpt, category, "readTime", "publishedAt", image, content) values');
  lines.push(blog.map(item => `  (${Number(item.id)}, ${sqlString(item.slug)}, ${sqlString(item.title)}, ${sqlString(item.excerpt)}, ${sqlString(item.category)}, ${sqlString(item.readTime)}, ${sqlString(item.publishedAt)}, ${sqlString(item.image)}, ${sqlString(item.content)})`).join(',\n') + ';');
  lines.push('');
}

const locationRows = Object.entries(locations);
if (locationRows.length) {
  lines.push('insert into public.locations (slug, name, region, description, "mapEmbedUrl", "subAreas") values');
  lines.push(locationRows.map(([slug, item]) => `  (${sqlString(slug)}, ${sqlString(item.name)}, ${sqlString(item.region)}, ${sqlString(item.description)}, ${sqlString(item.mapEmbedUrl)}, ${sqlJson(item.subAreas || [])})`).join(',\n') + ';');
  lines.push('');
}

const brandRows = Object.entries(brands);
if (brandRows.length) {
  lines.push('insert into public.brands (slug, title, description, image, premium) values');
  lines.push(brandRows.map(([slug, item]) => `  (${sqlString(slug)}, ${sqlString(item.title)}, ${sqlString(item.description)}, ${sqlString(item.image)}, ${item.premium ? 'true' : 'false'})`).join(',\n') + ';');
  lines.push('');
}

lines.push(`insert into public.contact (phone, "phoneHref", email, location, "socialMedia", reviews) values (${sqlString(contact.phone)}, ${sqlString(contact.phoneHref)}, ${sqlString(contact.email)}, ${sqlString(contact.location)}, ${sqlJson(contact.socialMedia || [])}, ${sqlJson(contact.reviews || {})});`);
lines.push('');

if (faq.length) {
  lines.push('insert into public.faq (question, answer) values');
  lines.push(faq.map(item => `  (${sqlString(item.question)}, ${sqlString(item.answer)})`).join(',\n') + ';');
  lines.push('');
}

lines.push(`insert into public.metadata (title, description, keywords) values (${sqlString(metadata.title)}, ${sqlString(metadata.description)}, ${sqlString(metadata.keywords)});`);
lines.push('');

const serviceDetailRows = Object.entries(serviceDetails);
if (serviceDetailRows.length) {
  lines.push('insert into public.service_details (slug, title, description, image) values');
  lines.push(serviceDetailRows.map(([slug, item]) => `  (${sqlString(slug)}, ${sqlString(item.title)}, ${sqlString(item.description)}, ${sqlString(item.image || null)})`).join(',\n') + ';');
  lines.push('');
}

if (servicesCommercial.length) {
  lines.push('insert into public.services_commercial (title, description, href, icon) values');
  lines.push(servicesCommercial.map(item => `  (${sqlString(item.title)}, ${sqlString(item.description)}, ${sqlString(item.href)}, ${sqlString(item.icon)})`).join(',\n') + ';');
  lines.push('');
}

if (servicesResidential.length) {
  lines.push('insert into public.services_residential (title, description, href, icon) values');
  lines.push(servicesResidential.map(item => `  (${sqlString(item.title)}, ${sqlString(item.description)}, ${sqlString(item.href)}, ${sqlString(item.icon)})`).join(',\n') + ';');
  lines.push('');
}

if (testimonials.length) {
  lines.push('insert into public.testimonials (initials, name, location, text, avatar) values');
  lines.push(testimonials.map(item => `  (${sqlString(item.initials || null)}, ${sqlString(item.name)}, ${sqlString(item.location || null)}, ${sqlString(item.text)}, ${sqlString(item.avatar || null)})`).join(',\n') + ';');
  lines.push('');
}

lines.push(`insert into public.why (features, stats) values (${sqlJson(why.features || [])}, ${sqlJson(why.stats || [])});`);
lines.push('');

const areaRows = [];
for (const [city, pages] of Object.entries(areas)) {
  if (!Array.isArray(pages)) continue;
  pages.forEach((page, pageIndex) => {
    if (!Array.isArray(page)) return;
    page.forEach((name) => {
      areaRows.push({ city, pageIndex, name });
    });
  });
}
if (areaRows.length) {
  lines.push('insert into public.areas (city, page_index, area_name) values');
  lines.push(areaRows.map(r => `  (${sqlString(r.city)}, ${r.pageIndex}, ${sqlString(r.name)})`).join(',\n') + ';');
  lines.push('');
}

lines.push('-- Default RLS (public read)');
lines.push('do $$');
lines.push('declare');
lines.push('  table_name text;');
lines.push('  table_names text[] := array[');
lines.push("    'contact',");
lines.push("    'blog',");
lines.push("    'services_residential',");
lines.push("    'services_commercial',");
lines.push("    'testimonials',");
lines.push("    'why',");
lines.push("    'areas',");
lines.push("    'locations',");
lines.push("    'faq',");
lines.push("    'brands',");
lines.push("    'metadata',");
lines.push("    'service_details'");
lines.push('  ];');
lines.push('begin');
lines.push('  foreach table_name in array table_names');
lines.push('  loop');
lines.push("    execute format('alter table public.%I enable row level security', table_name);");
lines.push('');
lines.push('    if not exists (');
lines.push('      select 1');
lines.push('      from pg_policies');
lines.push("      where schemaname = 'public'");
lines.push('        and tablename = table_name');
lines.push("        and policyname = 'public_read'");
lines.push('    ) then');
lines.push('      execute format(');
lines.push("        'create policy public_read on public.%I for select using (true)',");
lines.push('        table_name');
lines.push('      );');
lines.push('    end if;');
lines.push('  end loop;');
lines.push('end');
lines.push('$$;');

fs.writeFileSync(outFile, lines.join('\n') + '\n', 'utf8');
console.log('Generated', outFile);
